### ISSUE TITLE
Refactor and enforce 80 characters/line in the code base

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/OG-USA#106]
In attempting to come up to speed on the codebase, I've found it difficult to read the code because some of the lines are 200+ characters long. If all are OK with this idea, I would like to do a quick PR that enforces 80 characters/line in the code. This would result in a large number of changed lines of code in all .py files in Python/dynamic and below, but it would be a one-time thing. No other changes (e.g. code logic, function names, etc.) would happen in the PR, to make things as clean as possible. Any objections?

**Comment by jdebacker** [comment]
None from me.  I think this will help the readability of the code.

**Comment by talumbau** [comment]
addressed in https://github.com/OpenSourcePolicyCenter/dynamic/pull/123
