### ISSUE TITLE
Data serialization should be done with numpy.savez

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/OG-USA#117]
We are saving numpy arrays in the pickle files. Instead of using pickle files, which are a more general purpose serialization format, let's use `numpy.savez`:

http://docs.scipy.org/doc/numpy/reference/generated/numpy.savez.html

This is inherently a binary format, so we won't have the text/binary issues we had before. It's not a compressed format, but our data needs aren't significant right now.

**Comment by jdebacker** [comment]
Closing as it doesn't seem to important at this stage.
