### ISSUE TITLE
txfunc.py output

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#162]
The output from txfunc.py should be sure to include mean adjusted total income for each year in the budget window.  We need this to get our scaling factor in the OG model correct. 

cc @rickecon

**Comment by rickecon** [comment]
@jdebacker . OK, I'll add a 10-element numpy array with average total income to the dictionary in the pickle that txfunc.py outputs. That will be in my next PR.

**Comment by rickecon** [comment]
@jdebacker . Should we compute average income with the outliers removed, as we do to estimate the functions? Or should we leave them in. My inclination for computing average income is to leave the outliers in.

**Comment by jdebacker** [comment]
@rickecon That's right, with outliers in.  I thought we only censored with negative and very tiny income amounts, so that we didn't have extremely large positive or negative AETRs (i.e., we left in large income values).  In any case, yes, let's calculate average adjusted total income in each tax year over the full sample.

**Comment by rickecon** [comment]
@jdebacker. In my most recent pull request, the average total incomes are computed and saved in a pickle. We can close this issue if you are satisfied with the output.
