### ISSUE TITLE
Parameter metadata should be available to the ogusa user

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/OG-USA#180]
Similar to `taxcalc`, metadata for the parameters should be available to a user of `ogusa`. I would suggest that `get_parameters` take two additional arguments:

```
def get_parameters(baseline=False, user_modifiable=False, metadata=False):

```

The default behavior is unchanged. If the user passes `user_modifiable=True`, this would return those parameters that are modifiable by the user in `taxcalc+ogusa` simulations. If `metadata=True` is passed, this would return the metadata for each parameter, if it exists (similar to metadata in `current_law_policy.json` in `taxcalc`).

**Comment by brittainhard** [comment]
@PeterDSteinberg can you take a look at this one?

**Comment by jdebacker** [comment]
`get_parameters()` now takes a `metadata` argument.  However, I'm leaving open this issue since I do not know if it returns the info that was intended.  

@hdoupe any comments?
