### ISSUE TITLE
TPI initial guesses

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#190]
Try using different time paths for initial guess to see if helps with convergence speed and robustness.  In particular, try something like:

```
       rpath_init = np.zeros(T+S-1)
        r1 = 1.02 * r_ss
        cc_r = r1
        bb_r = - 2 * (r1 - r_ss) / (T - S)
        aa_r = -bb_r / (2 * (T - S))
        rpath_init[:T-S+1] = (aa_r * (np.arange(0, T-S+1) ** 2) +
                         (bb_r * np.arange(0, T-S+1)) + cc_r)
        rpath_init[T-S+1:] = r_ss
```

**Comment by jdebacker** [comment]
Testing this, we current initial guess for the time path works better than the above with population growth turned off.

When population dynamics are added back to the model, we might consider making the initial guess of the time path a function of the population dynamics.

**Comment by rickecon** [comment]
What matters most is the initial period value of the initial guess of the time path for r, w, T_H, and factor. These initial guesses need to be some factor greater-than or less-than their steady-state values. And the sign of that difference is simply a function of the initial state. Then we simply use the exponential path to the new steady-state in period T.

**Comment by jdebacker** [comment]
Ok - so in the ideal case, we have an exogenous initial state, pinned down by the data on capital and labor supply, and taxes in most recent year data available.  We solve model for SS.  Then we just use the exponential function connecting the initial state to SS (a form of which is already what we use in the current model) to make the guess for the time path.  No need to worry about pop dynamics.  This makes sense.

**Comment by jdebacker** [comment]
Closing.  I think we are ok for now.  TPI converge is seeming quite robust.
