### ISSUE TITLE
How to Add Effects on Individual States

### ISSUE THREAD

**Issue by kerkphil** [open-source-economics/OG-USA#22]
Treat states as small open economies which take the aggregate macro effects as given.  With detailed demographic information on each state, we can see how their set of households evolve over time and the federal tax burdens each household will pay.  Similarly, we should be able to find out the mix of industries in each state and approximate taxes from each of these.

Note we will need migration estimates into and out of each state, including (primarily) migration between states, but within the US.

**Comment by jdebacker** [comment]
Closing this issue for lack of interest.  Can reopen one on this topic if their is bandwidth to work on it.
