### ISSUE TITLE
Estimate tax functions from microdata that are monotonic in labor and capital income

### ISSUE THREAD

**Issue by rickecon** [open-source-economics/OG-USA#234]
We found that multiple equilibria resulting from multiple local optima result with our originally estimated tax functions. We estimated these functions to fit ETR, MTRx, and MTRy data from Tax-Calculator. This issue tracks the development and testing of a new functional form for the tax functions that fits the data well and has the properties necessary for a unique equilibrium that goes to the steady-state in the long run over the time path of the economy.

**Comment by rickecon** [comment]
First, we found good evidence that a functional form for tax rates that is monotonically increasing in labor income (x) and capital income (y), respectively, is not too strong an assumption. The following figures are two separate perspectives of the same scatterplot of effective tax rates (ETRs) as a function of labor income (x) and capital income (y) from Tax-Calculator for 43-year-olds in the year 2016.
![etr_age_43_year_2016_data](https://cloud.githubusercontent.com/assets/4317690/17530603/ddcd166a-5e3d-11e6-8733-cf08e58c01a4.png)
![etr_age_43_year_2016_data2](https://cloud.githubusercontent.com/assets/4317690/17530734/69c492a6-5e3e-11e6-816d-10d8d5b2e146.png)

The following four figures are the same two perspectives of the marginal tax rate of labor income and the marginal tax rate of capital income, respectely, both plotted as functions of both labor income (x) and capital income (y).

![mtrx_age_43_year_2016_data](https://cloud.githubusercontent.com/assets/4317690/17530894/27f14364-5e3f-11e6-97fe-c84d6f63c2f7.png)

![mtrx_age_43_year_2016_data2](https://cloud.githubusercontent.com/assets/4317690/17531034/d3a50218-5e3f-11e6-92b7-9a083571efd0.png)

![mtry_age_43_year_2016_data](https://cloud.githubusercontent.com/assets/4317690/17530907/359e24b4-5e3f-11e6-96ea-c5d272c97131.png)

![mtry_age_43_year_2016_data2](https://cloud.githubusercontent.com/assets/4317690/17531045/d97ef70c-5e3f-11e6-8a55-dbcfa0b95cb8.png)

The blue figure below is a 3D histogram showing that all the mass for these points is for low capital income with a skewed fat-right-tailed distribution over labor income. This density plot applies to all of the scatterplots above.
![hist_age_43_year_20162](https://cloud.githubusercontent.com/assets/4317690/17530889/1f5cd470-5e3f-11e6-81dc-e97da3138af7.png)

**Comment by rickecon** [comment]
The original tax function that we estimated looked like a good fit, but was not monotonically increasing in labor income (x) and capital income (y). The functional form was the following:

![](http://www.sciweavers.org/upload/Tex2Img_1470773328/eqn.png)

**Comment by rickecon** [comment]
I just finished trying a CES functional form that combines two univariate tax rate functions--tau(x) and tau(y)--both of which are monotonically increasing in their respective variables. The functional form was the following

![](http://www.sciweavers.org/upload/Tex2Img_1470773874/eqn.png)

This did not work because it is not well identified. The elasticity parameter epsilon changes the curvature of the fitted curve. This is also done by the parameters in the ratios of polynomials in tau(x) and tau(y). For this reason, I would get very different estimated parameters for whatever different starting values I chose.

Next, I will try to Cobb-Douglas case of the CES function where epsilon = 1.

**Comment by jdebacker** [comment]
The "C" parameter is not the same in \tau(x) and \tau(y), correct?

Also, can you normalize the constant to 1 in this specification?  Then adjust the other parameters accordingly?  It seems like you should be able to do this for \tau(x) or \tau(y) (and maybe both since alpha can adjust accordingly).  That might help with the identification.

**Comment by rickecon** [comment]
@jdebacker Yes. That is a typo above. The F parameter in the first specification, and the C parameters in the specifications above should be 1. I just edited both of those.

**Comment by rickecon** [comment]
@kerkphil How do you know how well that surface fits the data? If you have a population weighted sum of squared deviations, we can compare across runs. And what functional form are you using?

**Comment by kerkphil** [comment]
@rickecon  This is just eyeballing the function vs the data for ETR.  Both reach approximately the same minimum at the x=y=0 point, both assymptote to about the same levels on the x and y axes.  But, of course, a formal fitting needs to be done.  I used a CES function with the parameter values indicated.  My guess is that these would be good starting values for a formal fit via minimization of squared deviations.

**Comment by rickecon** [comment]
In my preliminary horse race between the Cobb-Douglas and the general CES above, I am getting lower weighted sum of squared deviations from the Cobb-Douglas specification (e.g. 8390 Cobb-Douglas versus 8491 general CES). My intuition for this is that, even though Cobb-Douglas is a nested version of the more general CES function, the minimizer is not able to find a global minimum in the latter case because the elasticity parameter performs the same curvature role as do the coefficients in the ratios of polynomials. We may still have an identification problem in the Cobb-Douglas functional form, but it is to a lesser degree than the general CES function. I think this is evidenced by the lower weighted sum of squared deviations.

**Comment by jdebacker** [comment]
What if you start the CES off with epsilon=1 an the min values from the CD estimation?  

I'll admit I do like the additional flexibility of the CES and am a bit surprised there is trouble finding a global min since epsilon should be affecting the function in a significantly different way than the ratio of polynomials.  E.g. you can think about the ratios defining the edges (i.e. what the tax functions look like when x or y=0).  Epsilon will tell you about the surface connecting those two edge, and the amount of curvature across that surface.

**Comment by rickecon** [comment]
OK. After much testing, I think the verdict is that that the general CES is not identified, even if we zero out the coefficients on the squared terms in the polynomials. I think this is evidence for using the Cobb-Douglas aggregator in which we estimate the max_x and max_y terms as well as the coefficients on the squared terms in the polynomials. The table below shows the sum of squared errors for the different specifications.
| Spec.   | Est.     | Incl.         |             | Spec.      | Est.    | Incl.         |              |
| num.    | maxes | sq. trms  | wSSE   | num.       | maxes | sq. trms | wSSE    |
| ------- | ------ | --------- | ------- | --------- | ------ | -------- | ------- |
|  1 (CD) |     No   |    Yes       | 8525.5 |   1 (CES) |    No   |  Yes        | 9935.5  |
| ** 2 (CD)** |   ** Yes**  |   ** Yes**       | **8418.1**  |   2 (CES) |   Yes   |  Yes        | 10075.5 |
|  3 (CD) |     No   |    No       | 8965.7 |   3 (CES) |    No   |  No         | 14607.7  |
|  4 (CD) |    Yes  |    No       | 8654.4  |   4 (CES) |   Yes   |  No         | 10214.0 |

**Comment by rickecon** [comment]
I estimated the ETR, MTRx, and MTRy functions with the Cobb-Douglas specification (2-CD, Figure 4 above), and the functional form performed very well. It was reliable and rubust, in passed the eye test, and it was very flexible. Below are six plots of the fit--two for each ETR, MTRx, and MTRy--to the data for 43-year-olds in 2016.

The first figure in the pair plots the full range of income. However, 99% of the data are much closer to the origin. So the second plot shows a zoom in of the fit for labor income and capital income less than $800,000. The fit is very good close to the origin where most of the data lie, and it passes the eyball test further out from the origin where things are more sparse.

Full income range predicted ETR vs. ETR data

?

Truncated income range (<$800K) predicted ETR vs. ETR data

?

Full income range predicted MTRx vs. MTRx data

?

Truncated income range (<$800K) predicted MTRx vs. MTRx data

?

Full income range predicted MTRy vs. MTRy data

?

Truncated income range (<$800K) predicted MTRy vs. MTRy data

?

**Comment by rickecon** [comment]
This functional form also works for a flat tax. As a test, I set all the ETR data to a constant 0.15. I used the same starting values for the parameters as in the previous runs, and the estimation came up with the following fit.
![flattaxfit](https://cloud.githubusercontent.com/assets/4317690/17603889/c89e780a-5fd8-11e6-8f47-96538ad7d6dc.png)

**Comment by rickecon** [comment]
@jdebacker @kerkphil . I just ran the new tax functions (age_specific=True) on OG-USA with S=80 and J=7. The steady-state solved, but the max resource constraint error in the last period of the time path was 2.7e-02. In trying to diagnose the problem, I am ran the following diagnostics.

1. **WORKS**. Set all ETR's, MTRx's, and MTRy's equal to their respective averages. I ran this with S=40 and J=3 and everything solved, both SS and TPI. All the plots of the time paths look right as well.

2. **DOESN'T WORK**. Set ETR's to average ETR, and limit MTRx's to be functions only of labor income and limit MTRy's to be functions only of capital income with S=40 and J=3. This one solves the SS nicely, but the final resource constraint error has not converged (-8.9e-03). Plots of the time paths have the same jump as the full run above. Not good.

3. **WORKS**. Let ETR's be functions of both labor income and capital income, but restrict MTRx's and MTRy's to be their respective averages with S=40 and J=3. Everything solved, both SS and TPI. All the plots of the time paths look right.

4. **DOESN'T WORK**. Let ETR's be functions of both labor income and capital income, but restrict MTRx's and MTRy's to be functions of labor income and capital income, respectively, with S=40 and J=3. This one solves the SS nicely, but the final resource constraint error has not converged (-8.1e-03). Plots of the time paths have the same jump as the full run above. Not good.

The conclusion is that the MTRx and MTRy functions being anything more than estimated constants is causing problems. Back to debugging land.

**Comment by rickecon** [comment]
The next test is to see if there is some interaction between the MTRx functions and the MTRy functions.

1. **WORKS**. Set ETR's and MTRx's equal to their respective averages, and let MTRy be a function of only capital income for S=40 and J=3. SS and TPI solve and all plots look good.

2. **DOESN'T WORK**. Set ETR's and MTRy's equal to their respective averages, and let MTRx be a function of only labor income for S=40 and J=3. This one won't even solve the SS. It starts given NaN's for the Euler error values after about 10 iterations.

**Comment by rickecon** [comment]
@jdebacker. I am really stumped. I ran the following tests, and neither of them worked. In both cases, the steady-state solved and TPI finished, but that last period resource constraint max error was too large (-1.06e-03 and ?, respectively).

1. **DOESN'T WORK**. Set MTRx's equal to the age 42 (approximately, 12th element, index 11, in the age dimension) parameter values so that MTRx was not a function of age, but was a function of both capital and labor income, respectively, according to the Cobb-Douglas specification. I let ETR's and MTRy's be the full functions of labor income and capital income for S=40 and J=3. SS solves and TPI solves, but the max resource constraint error in the last period of the TPI is -1.06-e03.

2. **DOESN'T WORK**. Made MTRx's a function of only labor income. I let ETR's and MTRy's be the full functions of labor income and capital income for S=40 and J=3. SS solves and TPI solves, but the max resource constraint error in the last period of the TPI is -8.09-e03.

Really stumped on this. The only specifications that work are with MTRx equal to its average.

**Comment by jdebacker** [comment]
@rickecon , I'll take a look.  Seems like it's an issue with how some MTRx parameters are being passed/entered into functions.

**Comment by rickecon** [comment]
@jdebacker @kerkphil . BOOM! Found it. Everything now runs for S=40 and J=3 with the SS and TPI solving to a very high precision using the full ETR, MTRx, and MTRy functions. Man, that sucked. It was a very pernicious coding error--a small transposition of function arguments in a key piece of code.

The wage (w) and savings (b) arguments were transposed in the tax.MTR_labor() function call in line 392 of household.py. This is what was causing all the trouble. I will run the S=80 and J=7 model overnight to make sure that it runs well. Then I will submit this PR. Thanks for all the help. This may solve a lot of the problems that we were seeing.

**Comment by jdebacker** [comment]
@rickecon - great find!  It looks like that error has been with us for a while.

**Comment by rickecon** [comment]
S=80 and J=7 works beautifully now with the full ETR, MTRx, MTRy functions of age, time, labor income, and capital income. Here are some pictures of the equilibrium time paths of aggregate variables.
![figi](https://cloud.githubusercontent.com/assets/4317690/18090955/a3f2d3d0-6e8c-11e6-940a-0125bae880ae.png)
![figk](https://cloud.githubusercontent.com/assets/4317690/18090965/abe28158-6e8c-11e6-9452-f0019a7600f3.png)
![figl](https://cloud.githubusercontent.com/assets/4317690/18090975/b031fe8c-6e8c-11e6-9228-9fcd1ddddc6d.png)

**Comment by rickecon** [comment]
Finshed via PR #238.
