### ISSUE TITLE
Open economy option

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#237]
Per a suggestion from Ken Judd, let's allow for an open economy option for OG-USA.

This means the interest rate is exogenous.  To accommodate this, we'll need to pass a boolean denoting open economy through to execute.py.  This will trigger calls of different SS and TPI scripts - ones where the "outer loops" (those that pin down prices) will now omit interest rates, since they will no longer be endogenous.

**Comment by salimfurth** [comment]
I've branched smallopen from master. I'm planning to work on this topic with @chrisrytting. Feel free to jump in and let me know if/when I'm making mistakes in workflow.

**Comment by rickecon** [comment]
@salimfurth and @chrisrytting welcome aboard.

**Comment by salimfurth** [comment]
Could @rickecon or @jdebacker satisfy my curiosity on two aspects of the broader model?
1. The SS model uses 4 moments to test for convergence. Is there a theoretical or practical reason these 4 were chosen? In the small_open model, we're effectively dropping to 3 tests, since r=r_new for every iteration. If we're worried about funny business at corner solutions we can add another test or two easily.
2. Why is steady state immigration negative (or am I reading it wrong)?

**Comment by rickecon** [comment]
The steady-state solution in the baseline model is really (2*S*J) + 4 equations and unknowns, where S is the number of periods an individual lives and J is the number of ability types. The 2*S*J variables are the S savings decisions and S labor supply decisions of each of J individuals over their respective lifetimes. The other four equations are basically characterizing equations for the interest rate (r), wage (w), lump sum transfer (T^H), and income factor (factor). These four equations are arrived at by substituting together combinations of market clearing conditions, firm's FOC's, and definitions that include those four variables (see "[Integration...](https://sites.google.com/site/rickecon/DEP_10pct.pdf)" paper). So the SS solution is not really four moments. It is an inner-loop that solves for the 2*S*J savings and labor supply decisions of households given r, w, T^H, and factor. Then we solve for the r, w, T^H, and factor using a bisection method. @salimfurth , feel free to call me if you want to chat.

**Comment by jdebacker** [comment]
@salimfurth , to answer your second question, let me ask what you are looking at?  Immigration rates are a vector of length S.  For some ages, in the SS, these are slightly negative.  Overall, the population is growing: `SS pop growth:  0.00129077232238`.

While it may seem odd that any immigration rates are negative, let me add:
1) Immigration rates for all ages are strictly positive (net in-migration) until 120 years from the current period.  It's hard to predict that far in the future, but one could imagine some net out-migration.
2) If we keep fertility and mortality rates constant over time, we have to adjust immigration in order for the population to become stationary at some point.  Alternatively, one could adjust mortality or fertility in the future, but we chose to adjust immigration since its future path may be less predictably anyway.

**Comment by rickecon** [comment]
@salimfurth . If you look at this figure of the estimated immigration rates, you'll notice three features.
1. Estimated immigration rates are small (most less than 0.7%), except for the very young and the very old. And there are very few people in that over-90 age category.
2. The adjusted immigration rates are very close to the original immigration rates.
3. A few adjusted immigration rates are negative for given ages, but are very close to zero. Only one original immigration rate is negative. Aggregate immigration rates are strongly positive.
![origvsadjimm](https://cloud.githubusercontent.com/assets/4317690/18523901/d9dfbd6e-7a7b-11e6-90f5-65b009538522.png)

**Comment by rickecon** [comment]
@salimfurth . See Appendix A-1 of the "[Integration...](https://sites.google.com/site/rickecon/DEP_10pct.pdf)" paper for a detailed description of the demographics.

**Comment by salimfurth** [comment]
Well this is odd: the discrepancy is associated with shrinking S. When I set S=40, I get a choppy, mostly negative immigration rate, in both the early periods and the steady state.

![immrates](https://cloud.githubusercontent.com/assets/16611986/18526078/1f1b484c-7a8d-11e6-9253-151e8099061e.png)

Inside SS_solver (where I encountered the adjustments associated with immigration), I calculated (omega_SS*imm_rates).sum() = -0.0084.

But when I set S=80, I get a graph like the one you posted, and omega_SS*imm_rates).sum() = 0.0024. So it flips immigration's impact on demographics by a full percentage point.


I'm not sure this is a problem at all. It might resolve if I

**Comment by salimfurth** [comment]
Ignore that last incomplete sentence.

**Comment by salimfurth** [comment]
For completeness, I should note that switching between J = 2 and J = 7 makes no difference; the immigration reversal is driven by the change in S.

Over the range where it solves (20<S<81), steady state immigration appears to be a monotonic, increasing function of S that is zero at S=66. I don't know if that's worrisome. (Tagging @jdebacker & @rickecon).

**Comment by rickecon** [comment]
@salimfurth No, not worrisome. This is a known issue with the demographics. Because the immigration rates are essentially a residual, more is required of each immigration rate i_s for a particular age when the size of each period gets larger (S gets smaller). So it is intuitive that immigration rates and mortality rates would get larger as the size of a period gets larger, because both of those rates are cumulative. That more immigration rates are negative simply means that current mortality rates and fertility rates need to be tamped down more in order to match population dynamics.

**Comment by rickecon** [comment]
Any demographic approach has its problems. This model allows one to put in whatever demographics one wants.

The leading approach is Nishiyama and Smetters (_QJE_, 2007) and Nishiyama (_JEDC_, 2015). They use a method in which they project changing fertility, mortality, and immigration rates by age over time (this is what the Soc. Sec. Admin. does). Two problems are that it is hard to forecast how fertility and mortality rates will change, and we don't have good data on immigration rates by age.

One of the strengths of our approach is that it backs out implied immigration rates, where we might not be very confident in immigration rates taken directly from the data. One could argue that holding those rates constant over time is too strong an assumption. But we could change the model to allow for those rates to change.

**Comment by salimfurth** [comment]
I just realized that all my commits aren't showing up on GitHub online - I'm using the GitHub shell application on this computer to manage things. It seems like the problem might be that I accidentally branched from open-source-economics/OG-USA instead of from salimfurth/OG-USA as intended. Thus, it lets me "commit" on the GitHub shell but I guess that doesn't get saved on any repo. It won't let me "publish". How should I proceed, since I don't want to lose my work?

**Comment by jdebacker** [comment]
@salimfurth - what I would do is the following:
1) Save `repos/OG-USA` in another directory (e.g. `repos/backup/OG-USA`)
2) Delete `repos/OG-USA`
3) Clone your fork to `repos/OG-USA` : `git clone https://github.com/salimfurth/OG-USA.git`
4) from your repo, checkout the branch you want to work in (e.g. `checkout -b open_econ`)
5) Copy the files from `repos/backup/OG-USA` that you had changed into `repos/OG-USA`
6) Stage your files for commit: `git add path\filename`
6) Commit your changes: `git commit -m "changes to start open economy model"`
7) Push changes to remote repo: `git push origin open_econ` (replace `open_econ` with whatever your branch name is)
8) Open PR when ready

BTW, there's a little learning curve, but I recommend using the command line for your git workflow.

**Comment by salimfurth** [comment]
What's the advantage of command line? I find myself making constant typing errors, unable to track what's going on, etc, constantly. It also doesn't track past actions, so I'm always pretty lost when I start doing anything in it. There have to be some major advantages to overcome a setup that is so conducive to human error.

**Comment by jdebacker** [comment]
@salimfurth , look for email

**Comment by jdebacker** [comment]
Great.  I'll pull your fork down and run on my machine - maybe tonight.  Thanks!

**Comment by salimfurth** [comment]
One of the things I added was distinct firm versus household interest rates within the small_open framework. That allows households to face an unmodeled financial friction which lowers their rate of return relative to the firm's rental rate.

**Comment by jdebacker** [comment]
@salimfurth a few comments:
1) I was able to run your code just fine on a Mac.
2) SS and TPI results for the baseline seem reasonable, but it might be a good idea to compare to the same baseline without the open econ assumption.
3) When I run the baseline and reform and calculate percentage changes in the factor prices and economic aggregates, I get very little (essentially zero) change for all to these series.  @rickecon  - can you remind me what is in the reform tax function pickle in this repo?  The  10% cut? Something else?  My prior was that the responses to a tax cut would be larger in the open economy model.

Re the financial friction. I like this idea and it seems to fit easily in here.  But what happens to that wedge?  I suppose you model it as a real cost - the difference between what the firms pay for rent and what the households get leaves the economy.  Is there good reason to do this rather than model the wedge as being due to traditions costs - so that the income is returned to the households, but via a financial intermediary rather than from a goods producing firm?

**Comment by salimfurth** [comment]
Thanks, @jdebacker!

On the financial friction, the disappearing wedge makes sense when the financial sector is elsewhere. So for applications where the economy modeled is a state or a small country, it's sensible to assume that some intermediation is done by distant bankers and is costly, but not worth modeling in explicit detail. Obviously, a full financial sector buildout would be useful for some applications, but that would more naturally take place within the closed economy model.

**Comment by salimfurth** [comment]
And, @jdebacker, regarding the "Reform" option, I don't actually think there *is* a reform, at least not in the run_micro:False environment where I'm working.

**Comment by jdebacker** [comment]
@salimfurth, `run_micro:False` referee to whether tax functions are estimated from the micro data.  If this is false, you  can still run a reform, you just need to have tax function parameters that summarize the reform.  In your case, I'm uncommenting the reform run in `run_ogusa_serial.py`.  The script then looks for the `TxFuncEst_policy.pkl' file with the reform parameters.  Thing is, I can't remember what the reform was that these parameters came from.  I think it's a reform @rickecon ran recently, though.

**Comment by salimfurth** [comment]
@jdebacker, I ran the code on both TxFuncEst_policy.pkl and TxFuncEst_baseline.pkl (with `small_econ:False` and `guid:''` in both cases) and got identical steady states. When I leave `guid:'mtr_38'` in the reform, it looks for another path and can't find the pickle file it wants.

**Comment by rickecon** [comment]
@salimfurth . The current versions of `TxFuncEst_baseline.pkl` and `TxFuncEst_policy.pkl` are currently identical. The `guid' is a dictionary item that adds suffixes to those files so that multiple reforms can happen at once and still be differentiated from one another. So for any current runs, leave `guid:''`. Also, I will e-mail you a `TxFuncEst_policy.pkl` that is different from the current `TxFuncEst_baseline.pkl`. This file comes from the experiment that we ran in the "[Integration...](https://sites.google.com/site/rickecon/DEP_10pct.pdf)" paper.

**Comment by jdebacker** [comment]
@salimfurth Try [this](https://github.com/rickecon/TaxFuncIntegr/blob/master/Python/TxFuncEst_policyint.pkl) pickle for the policy.  It's a 10% reduction in all marginal rates on ordinary income and a doubling of the standard deduction.  I think a good check is to run the baseline and reform through (so make sure lines 86-97 and line 107 are uncommented in `run_ogusa_serial.py`.  Also, add: `np.savetxt('OpenEconPctChanges.csv',pct_changes,delimiter=",")` after line 48 in `postprocess.py` to save the percentage changes to a csv file.  We can then compare to the closed economy version.

**Comment by jdebacker** [comment]
@rickecon ^

**Comment by rickecon** [comment]
@jdebacker , @salimfurth . We had left those two baseline and policy tax function pickles the same because they were only used for the Travis CI automatic testing of pull requests.

**Comment by salimfurth** [comment]
Here are the results of reforms in Closed and Open economies, and the difference between Closed and Open with r=0.033.

![deltas](https://cloud.githubusercontent.com/assets/16611986/18970965/53db8e4a-8661-11e6-882a-
a5fb2acdfcb8.png)

**Comment by salimfurth** [comment]
That didn't work; trying again. This used @jdebacker's reform above, btw. 

![deltas](https://cloud.githubusercontent.com/assets/16611986/18971045/9d0b7f76-8661-11e6-8c15-7c40f699217f.png)

**Comment by jdebacker** [comment]
@salimfurth - why no change in wages with the open economy model?

**Comment by salimfurth** [comment]
I think that's just a standard open-economy result, @jdebacker. 

From the firm's FOC for capital, the capital-labor ratio can be expressed as a function of r and parameters.

Combining the two FOC's, the wage rate can be expressed as a function of parameters, K/L, and r. Importantly, labor taxes don't enter into the labor demand curve. Thus, when r is fixed by world markets, pretax wages are fully determined by world markets.

A linear increase in capital taxes is easy to include, since it just shifts the exogenous r. But taxes levied at the firm level in nonlinear fashion can clearly distort this nice representative-firm math.

**Comment by jdebacker** [comment]
@salimfurth Thanks for the explanation.  This make sense.

**Comment by jdebacker** [comment]
@salimfurth Do we have any outstanding questions here?  If not, want to go ahead and open a PR?

**Comment by salimfurth** [comment]
@jdebacker, I don't know what questions to ask. I'm happy to open a PR if you guys are satisfied, but I don't feel qualified to say I have confidence in the model.

**Comment by jdebacker** [comment]
Closed via PR #249
