### ISSUE TITLE
Smaller state space for testing

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#262]
The model now runs for a general S and J.  

Let's allow the user to call a version with small S and J to run quickly to test program through TPI. To do this, I propose:

1) Clean up `parameters.py` to remove the `get_reduced_parameters()` function.  
2) Allow a keyword to be passed to `execute.runner` to run a "test version" that will choose a small S and J, which will allow for a quick model solution (all other parameters can remain the same).
3) Get rid of `execute_small.py` and calls to it in current testing programs. 

Something to check:
- That the above works when pre-estimated tax functions that vary by age are ready in.

CC @PeterDSteinberg , @rickecon

**Comment by PeterDSteinberg** [comment]
@jdebacker Is this issue resolved with merge of #264?  Also, can you paste here how I can run from the command line one of the quickest OG-USA simulations?

**Comment by jdebacker** [comment]
Resolved via PR #264
