### ISSUE TITLE
Model solution with zero growth?

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#269]
If  I set the parameter `g_y_annual=0.0`, I find that the model does not find a SS solution.  I've attempted this with `budget_balance=True/False` under the closed economy specification.

This issue is to confirm this issue among others runs/configurations and to discuss solutions.

**Comment by salimfurth** [comment]
I find that the equilibrium interest rate is negative using the default parameters for `test`. But when I lower `debt_ratio_ss` to 0.5 from 1.0, it finds a solution (with a very, very low interest rate).

**Comment by jdebacker** [comment]
Ok - thanks for looking at that.  

Relatedly, I've been working to make the production function a more general CES function.  Under certain parameterizations, when doing that I was also running into issues where a negative interest rate was found given the initial guesses and the root finder couldn't get out of the space and therefore the SS solution failed.    

It sounds like the solution to both these problems to to ensure that initial guesses are "reasonable" in that they do not generate negatives for the factor prices or aggregate quantities.  We might also need to improve the methods to prevent the root finder from going to these spaces also.

cc @rickecon

**Comment by salimfurth** [comment]
Unlike you, I'm finding a solution when `budget_balance=False`. It starts out with a negative interest rate in the guess, but then finds its way to a (small) positive one and yields a steady state solution.

**Comment by jdebacker** [comment]
Closing.  My error must have been to some changes in branch I was working with.
