### ISSUE TITLE
Using the assignment operator

### ISSUE THREAD

**Issue by salimfurth** [open-source-economics/OG-USA#270]
I ran into the Python oddity where 
`a = b`
does not have the same result as
`a = b*1.0`

As I'm sure @jdebacker and @rickecon know, the former is the assignment operator. That means that in programming, if `b` later changes, the value of `a` also changes, because it refers to the same place in memory.

We have a number of places in the OG-USA code where we are using this operator, and I think it's not intended. E.g., things like `rnew = r`. I don't think these are causing havoc presently, but they could. I suggest amending to `rnew = r[:]`, which copies the data in `r` rather than creating another reference to that spot in memory.

Am I misreading elegant code that used this feature (bug?) purposely? Thanks.

**Comment by PeterDSteinberg** [comment]
It is a good idea to check through the code for use of such assignment as reference (e.g. `a = b`), but only in cases where `b` is mutable object like a list, set, dict, numpy array, or dataframe.  For most scalar data types it is not an issue.  There have been several times on other projects I worked on where forgetting about references to mutable objects caused hidden bugs.

**Comment by salimfurth** [comment]
In some cases, we are switching out scalars for arrays in order to let things time-vary. It's worth keeping an eye out for.

**Comment by rickecon** [comment]
@salimfurth . @jdebacker and I learned/realized/saw this issue about 9 months ago. We combed through the code to see if there were any problems, but could not find any. This is an artifact of this code base being born over three years ago, before we fully understood the intricacies of Python. I think the preferred method for numpy arrays is the `.copy()` method, e.g., `rnew = r.copy()`.
