### ISSUE TITLE
income.py Arctangent fits

### ISSUE THREAD

**Issue by evan-magnusson** [open-source-economics/OG-USA#28]
The arctan fit does not converge for a few of the groups -- fix the code so that it does.

**Comment by evan-magnusson** [comment]
Again, if we don't use the polynomial fits, but just the data itself, this isn't an issue.

**Comment by evan-magnusson** [comment]
Perhaps we should use something besides an arctan.  As we talked about tuesday, since this is people aged 80-100, the exact shape doesn't matter much.  For simplicity and robustness, we could just do a linear fit, either with no depreciation or to some fraction for all ability types.

**Comment by rickecon** [comment]
This is fixed.
