### ISSUE TITLE
Baseline budget questions

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#280]
@salimfurth I have a couple questions to help me understand the recent addition of the `baseline_spending` option.

1) I see that `Gss` is endogenous.  Thus `Gss` potentially differs between the baseline and reform runs (i.e. the `baseline_spending=True` option only holds `T_Hss` constant between the baseline and reform policies equilibria).  However, this seems inconsistent with how I read the TP solution where `Gbaseline` is only read in from the baseline policy run.  So when one solves the TP for the reform policy, there seems to be an inconsistency between the time path of `G` and the steady state value that was solved for under the reform.  Why isn't just the path for `T_H` taken a exogenous and then one solves for the path of G and D that are consistent with this?

2) Related to the above, I am not seeing why one needs to compute the distance between `D` and `Dnew` in the TPI criterion when `baseline_spending=True`.  It seems like given the usual set of variables guessed in the time path (`r, w, BQ, T_H`) one can then solve for the paths of `G` and `D`.  That is, I don't see why `D` needs to be guessed separately since it is determined by the other variables.  What am I missing here?

**Comment by salimfurth** [comment]
@jdebacker:

1. `G` is only exogenous up to period `tG1`. After that, it follows the same rules regardless of the value of `baseline_spending`. This is all contained within `fiscal.py`.
2. In testing, I found that the model was solving prematurely. When `small_open = True`, `baseline_spending=True`, and `baseline=False`, `r` and `T_H` are both fixed, and `w` is closely tied to `r`, so the model was closing before actually converging.

**Comment by jdebacker** [comment]
@salimfurth said:

> G is only exogenous up to period tG1. After that, it follows the same rules regardless of the value of baseline_spending. This is all contained within fiscal.py.

Ok-  got it now.  Thanks.

> In testing, I found that the model was solving prematurely. When small_open = True, baseline_spending=True, and baseline=False, r and T_H are both fixed, and w is closely tied to r, so the model was closing before actually converging.

Can you explain more what you mean by "closing" by "not converging"?

**Comment by salimfurth** [comment]
Yes. The model had converged in the sense that `(r, w, BQ, TH)` was constant across two iterations, but it had not actually found a solution, and thus failed the resource constraint check or a simple eyeball test. That tuple is not a sufficient statistic for the larger model.

**Comment by salimfurth** [comment]
Also, related in spirit to (1) above, in a few of my simulations I've had last-period jumps, particularly in capital (magnitude circa 3e-4). The jumps are small enough that they can't be detected when test=True, and I haven't had time to follow up. I'm not sure if jumps are happening on any shared branches or only on the branch where I did my investment wedge project.

**Comment by jdebacker** [comment]
Hmm, I'll have to think about this - it seems like all the equations are there.

It may be related - I think I found an issue with `Y` not being updated in the TPI loop.  I've fixed that and am running some tests now to confirm that was an issue.
