### ISSUE TITLE
Growth rate

### ISSUE THREAD

**Issue by salimfurth** [open-source-economics/OG-USA#281]
@jdebacker and @rickecon: is there a reason for choosing `g_y_annual = 0.03` as the default value of technology growth? This seems two to three times the correct value for technology growth. CBO in January projects that Potential TFP growth for 2017-2027 will average 1.1 percent per year. They estimated that 
Potential TFP percent per year  per year from 1950-2016.

Obviously it's easy to change this as a user, but I'm concerned that there's a difference in definitions that I'm missing.

**Comment by jdebacker** [comment]
This is a user defined parameter, as Salim points out, so closing the issue.  Though will revisit in future calibration exercises of default parameter values.
