### ISSUE TITLE
income.py vs. Income_nopoly.py

### ISSUE THREAD

**Issue by evan-magnusson** [open-source-economics/OG-USA#29]
Income.py has a better fit, using polynomials which Jason computed.  However, we only have the polynomials for the 7 percentile groups used in the wealth tax paper.  Unless we can get polynomial fits for all percentile groups, we should stop using income.py, and move to income_nopoly, which just uses the raw data.

**Comment by jdebacker** [comment]
This is a good point.  We need to discuss, but I think we may want to use publicly available data for the calibration of the dynamic scoring model.  In that case, we use PSID data and will be creating calibration programs that can be run along side the dynamic scoring model.  For example, the calibration can be redone if the user defined new lifetime income/ability groupings.

**Comment by talumbau** [comment]
Is is reasonable to have a configuration flag for this? I am currently refactoring the TESTED_DONT_TOUCH directory and wondering if I should include both options.

**Comment by evan-magnusson** [comment]
I don't think so.  I think we'll use one and delete the other in the long term.  We'll just use _polynomials until we decide which one.

@jdebacker What do you think?

**Comment by rickecon** [comment]
This is solved in the current income.py.
