### ISSUE TITLE
consider alternative methods for passing parameters 

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#301]
We currently pass parameters to functions via tuples.  This can result in bugs as the oder these parameters are passed is critical and easy to confuse.

This issue is to discuss the pros and cons of alternative methods of passing parameters to functions.  Two to consider are:
- Dictionaries
- Named tuples

cc @rickecon

**Comment by talumbau** [comment]
You could have a convention that all function calls need to use keyword args to match up argument name with value. If you wanted to put everything in dictionaries, you can always pass that to functions using the "splat" operator: 

'''
my_func(**some_dict)
'''

**Comment by jdebacker** [comment]
One issue is how to unpack the objects in the dictionary for use with in a function.  Calling each parameters a `some_dict['param1'], some_dict['param2']` etc. can make the operations with in the function difficult to read (e.g., for a long equation).

What is the best way to unpack these objects?  It would be nice if something like the following loop would work:
```
param_dict = {'alpha': 0.1, 'beta': 0.9, 'delta': 0.05, 'omega': 0.55}
var_list = ('alpha', 'beta',  'omega')
for item in var_list:
    item = param_dict[item]
```

But it seems that you can't use `item` to create an new object that updates with each iteration (rather, running the above, an object called `item` is set at each iteration in the for loop (what I would want is that objects called `alpha`, `beta`, `omega` are created and set to the appropriate values from the dictionary.    Is there a way to do this?

**Comment by jdebacker** [comment]
It seems like unpacking dictionaries might be too much trouble to make it worthwhile relative to our current methods of passing tuples of parameters to functions. 

Closing this issue.
