### ISSUE TITLE
Consider different strategies for speeding up convergence

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/OG-USA#310]
Two basic ideas:
 * Easier speed up: @jdebacker has some ideas for where the code can be broken up into embarassingly parallel tasks to be run in multiprocessing.  These tasks are currently being run in serial.  Let's look into using `dask` for parallelism, even if the parallelism is only on one machine for now.  `dask` can use multiprocessing or multithreading on a single machine or distributed processing on multiple machines.  It's easier than using the multiprocessing library directly.
 * Alternative numerical methods: I can do some research on this idea eventually, such as 4th/6th order Runge Kuttta, Crank-MacCormack, Lax Friedrich's predictor corrector methods, but the `dask` multiprocessing idea above is a lower work per payoff option for now.

**Comment by rickecon** [comment]
@PeterDSteinberg. I like the idea of using `dask` for a more efficient use of multiprocessing that simply using the `multiprocessing` library. But I am also interested in architecture that can easily take our code and parallelize it on a big "academic" cluster (e.g., Midway at the University of Chicago, Blue Waters at Urbana-Champaign) as well as on a commercial cloud (AWS, Azure, Google Cloud). @jdebacker

**Comment by PeterDSteinberg** [comment]
@rickecon `dask` can do that kind of thing (running on top of your academic cluster or cloud provider's cluster).  `dask` is a lightweight parallelism framework that uses a graph of functions and their arguments, allowing delayed execution of those graphs 1) in distributed form like you describe, 2) multiprocessing or multithreading on one machine, or 3) in serial on one machine.  This makes it easy to write `dask` into our workflow here without interruption of our existing local usage of OG-USA and just doing some minor configuration on your cluster(s) to change how the code gets run.

The basic idea is:
 * We modify OG-USA to use dask for the parallel approach.  Several strategies exist here:
    * [delayed](http://dask.pydata.org/en/latest/delayed-overview.html) as a function decorator
    * [`dask.DataFrame`](http://dask.pydata.org/en/latest/dataframe.html) for pandas-like `DataFrame` operations but at larger scale (see also the other data structures on [dask.pydata.org](dask.pydata.org) like `Bag` and `Array`
    * [custom graphs](http://dask.pydata.org/en/latest/custom-graphs.html).  I have done this a number of times.  It involves writing out a dictionary of keys that identify outputs and values that are  tuples like `(function_handle, arg1 , arg2)`
 * We install dask with conda on your cluster(s) and there are tools that help out in a variety of situations for this, like [dask-ec2](https://github.com/dask/dask-ec2) and [other scheduler / worker setup ideas here](https://distributed.readthedocs.io/en/latest/setup.html).  Some of the setup tools do the following two bulleted steps, or they can be done manually if just installing dask with conda like any other package
 * On one cluster node we do `dask-scheduler` and that runs the scheduler that sends tasks out to workers
 * On other clusters we run `dask-worker 1.2.3.4` replacing `1.2.3.4:8786` with the `dask-scheduler` hostname:port

**Comment by rickecon** [comment]
@PeterDSteinberg. That sounds great. I am excited to explore the capabilities of `dask`.

**Comment by jdebacker** [comment]
This discussion has been moved to Issue #224
