### ISSUE TITLE
OG-USA new release after 0.5.9?

### ISSUE THREAD

**Issue by hdoupe** [open-source-economics/OG-USA#321]
Do we want to release a new version of OG-USA for [TaxBrain reinstatement](https://github.com/OpenSourcePolicyCenter/PolicyBrain/pull/710)?  

I think that this release would include PR's #305, #308, #311, #312, #313, and #315.  One more PR may be necessary to set the path to the PUF file or to take the PUF dataframe as an argument in `execute.runner` and pass that to Tax-Calculator in `get_micro_data.get_calculator`.

@PeterDSteinberg @rickecon @PeterDSteinberg

**Comment by PeterDSteinberg** [comment]
I am not as familiar with the PRs you listed above @hdoupe .  We are also currently working on OG-USA related changes for webapp's issues https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/481 and https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/482 . We hope to wrap those new features up this week for 481 and 482.  Maybe deploy after those are addressed?  Or two deploys?

**Comment by hdoupe** [comment]
Ok, I think we are going to be pretty tight on time if we try to include OpenSourcePolicyCenter/PolicyBrain#481 and OpenSourcePolicyCenter/PolicyBrain#482 in the next release on Friday.  We are on a pretty tight release schedule through the rest of the year.  A CPS option and UBI parameters need to be added by the end of the year.  So, I'm wary of two things:

1. Rushing these features in on Friday and running into bugs 
2. Waiting to release until after these features have been merged and then falling behind on our release schedule

It seems to me that the best course of action is to release without OG-USA on Friday and to incorporate it in the next release.  This means that it would not be added for about 3 weeks.

@PeterDSteinberg @jdebacker @rickecon @brittainhard @MattHJensen  what are your thoughts?

**Comment by PeterDSteinberg** [comment]
@hdoupe I was just about to email you.  I spoke with @brittainhard and agree we should not try to get 481 and 482 fixed by Friday.  Also Brittain and I need to rebase the work we have done for 481 on your https://github.com/OpenSourcePolicyCenter/PolicyBrain/pull/710 .  We can go ahead and branch off that Policybrain PR 710 then when 710 is merged we can pull master into our fixes for 481, 482.  That way we can get it ready for merge by Friday but have 3 weeks for testing on test app.

**Comment by hdoupe** [comment]
I think this has been resolved. Closing #321
