### ISSUE TITLE
Investment in OG-USA output

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#333]
We compute *domestic* investment only in `aggregates.get_I()`.  That is appropriate for checking the resource constraint, but is not what we want to be reporting in the OG-USA output.  We should update the dictionary from TPI.py to include domestic *and* total investment (which can include foreign flows of capital).

The calculation for total investment will be much simpler and can be done with the aggregate capital stocks: `I= K_{t+1} - (1-\delta)K_{t}`

**Comment by kerkphil** [comment]
We should probably do both.  The difference between the two will be movements in the international financial account, which should also be reported.  You are correct that the one we call 'investment' should be I= K_{t+1} - (1-\delta)K_{t}.

**Comment by jdebacker** [comment]
Addressed with PR #341
