### ISSUE TITLE
Can this project upgrade to Python 3.6?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/OG-USA#357]
The Pandas developers seem to be planning to quit supporting Python 2.7 at the end of 2018 as described [here](https://github.com/pandas-dev/pandas/issues/18894).  In the coming months the Tax-Calculator developers would like to transition Tax-Calculator to be a Python 3.6+ project.

**Will this project find it acceptable to have access to only Python 3.6 taxcalc packages?**

**Comment by jdebacker** [comment]
Yes.  We need to update OG-USA to be compatible with 3.6, but are planning to do so in the next few months.

**Comment by martinholmer** [comment]
@jdebacker said:
> Yes. We need to update OG-USA to be compatible with 3.6, but are planning to do so in the next few months.

OK, great!  Thanks for the quick response.
