### ISSUE TITLE
How to use CPS option?

### ISSUE THREAD

**Issue by rickecon** [open-source-economics/OG-USA#375]
@jdebacker. We need an option in the `runner` `kwargs` to select the CPS data vs. the PUF data. I don't know how to select that in our `Tax-Calculator` interface. @asmockler.

**Comment by jdebacker** [comment]
It's there.  Is the `data` `kwarg`.  Set `'data': 'cps'` to run with CPS data.  See example script in `./run_examples/run_ogusa_example.py`.

**Comment by rickecon** [comment]
Thanks @jdebacker. @asmockler.
