### ISSUE TITLE
CPS test data

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#387]
We have some CPS data in this repo for testing purposes.   Instead, we might consider just using the `CPS_constructor()` from Tax-Calc.  If this works, we can remove these data from the repo.

To do this, we need to update `test_basic.py`, among other scripts.

cc @hdoupe

**Comment by hdoupe** [comment]
What do you think the options should be? One way to do this is:

- `data=None` implies use the CPS and cps records constructor
- `data='path/to/data.csv'` use the file that is at this location (it could be the PUF or CPS)

We currently have the following options:
- `data=None` implies use the PUF file in the current directory
- `data='cps'` implies use the cps records constructor
- `data='path/to/data.csv'` implies use the file that is at this location (it could be the PUF or CPS)

**Comment by jdebacker** [comment]
I think what we've got now is just fine.  Users can easily specify CPS or another data file.  Closing this issue as a results.
