### ISSUE TITLE
Version of the newest OG-USA package is not confidence inspiring

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/OG-USA#394]
Now that TaxBrain 1.6.0 is working with OG-USA again, I downloaded the taxcalc, btax, and ogusa packages.
Here is what I get:
```
iMac:~ mrh$ python
Python 2.7.15 |Anaconda custom (64-bit)| (default, May  1 2018, 18:37:05) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import taxcalc as tc
>>> import btax at bt
>>> import ogusa as og
>>> tc.__version__
'0.20.1'
>>> bt.__version__
u'0.2.2'
>>> og.__version__
u'0.5.11+0.g007e598.dirty'
>>> exit()
```
I know it is just cosmetic, but the `+0.g007e598.dirty` suffix might be a little off-putting for someone trying to use the package for the first time.  Does the suffix add important information?  What exactly is `dirty` about the package?

**Comment by jdebacker** [comment]
@martinholmer I think this just means that the package you've compiles is version 0.5.11 with additional changes (i.e., there have been new commits merged into the master, but a new version has not been tagged).

**Comment by martinholmer** [comment]
@jdebacker said:
>  I think this just means that the package you've compiled is version 0.5.11 with additional changes (i.e., there have been new commits merged into the master, but a new version has not been tagged).

I have never "compiled" my own version of the ogusa package.  
What I downloaded is the "official" version available at Anaconda.
Here is what I did:
```
iMac:~ mrh$ conda search -c ospc ogusa
Loading channels: done
# Name                  Version           Build  Channel             
ogusa                     0.1.1          py27_0  ospc                
ogusa                       0.4          py27_0  ospc                
ogusa                       0.5          py27_0  ospc                
ogusa                     0.5.1          py27_0  ospc                
ogusa                     0.5.2          py27_0  ospc                
ogusa                     0.5.3          py27_0  ospc                
ogusa                     0.5.4          py27_0  ospc                
ogusa                     0.5.5          py27_0  ospc                
ogusa                     0.5.5          py27_2  ospc                
ogusa                     0.5.6          py27_0  ospc                
ogusa                     0.5.7          py27_0  ospc                
ogusa                    0.5.11          py27_0  ospc                
ogusa                    0.5.11          py36_0  ospc                

iMac:~ mrh$ conda list ogusa
# packages in environment at /Users/mrh/anaconda3:
#
# Name                    Version                   Build  Channel

iMac:~ mrh$ conda install -c ospc ogusa
Solving environment: done
## Package Plan ##
  environment location: /Users/mrh/anaconda3
  added / updated specs: 
    - ogusa
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    ogusa-0.5.11               |           py36_0         684 KB  ospc
The following NEW packages will be INSTALLED:
    ogusa:   0.5.11-py36_0 ospc
    taxcalc: 0.21.0-py36_0 ospc
Proceed ([y]/n)? y
Downloading and Extracting Packages
ogusa-0.5.11         | 684 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

iMac:~ mrh$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import taxcalc as tc
>>> tc.__version__
'0.21.0'
>>> import ogusa as og
>>> og.__version__
'0.5.11+0.g007e598.dirty' . <========================= PROBLEM HERE ============
>>> exit()
iMac:~ mrh$ 
```
So, you misunderstood my point because you thought I did something strange on my computer.

I still maintain that the name of the most-recent "official" version of the OG-USA package is not confidence inspiring.  Would you feel confident using a package that contains `dirty` in its name?

It fine to close this issue, but you might try to fix this problem.  How did you generate the latest ogusa package?

@hdoupe

**Comment by jdebacker** [comment]
@martinholmer Thanks for the detail on what you did - I guess it wasn't clear to me from your original post that the package was downloaded directly from Anaconda and not from this repo.

We will try to be more careful about tagging versions just before upload to Anaconda.  I know there were a bunch of issues creating the last conda package, so it may have to do with an additional commit that didn't effect the model but was necessary to get the package to build and we missed updating the tag.
