### ISSUE TITLE
Generalize code so it works for any S and J

### ISSUE THREAD

**Issue by evan-magnusson** [open-source-economics/OG-USA#42]
Many parts of the code, especially those dealing with the calibration (such as func_to_min in SS.py) only work for J=7 or S=80.  We need to go through the code and get rid of these problems eventually.

**Comment by evan-magnusson** [comment]
Removed this issue in func_to_min in SS.py, as well as the portion of the code in SS.py that checks the wealth fits.

**Comment by evan-magnusson** [comment]
List of places where this needs to occur:

labor_data.py: the labor data only has labor rates for ages 20 to 80, so we fit the next 20.  We need to then be able to change this for any S.

income_polynomials.py and income_nopoly.py: both assume S=80, there is no method for changing the income distribution if S != 80.

run_baseline.py: assumes that J=7 for the loop calibration (bumps, keep_changing, and chi_b_init_guesses are both size 7, and only work for this calibration).

SS.py: Assumes chi_n_guess is size 80.  Assumes chi_guesses is size 7.

**Comment by evan-magnusson** [comment]
Now that we have removed the loop calibration, run_baseline.py no longer assumes that J=7

**Comment by jdebacker** [comment]
This has been fixed via PR #231
