### ISSUE TITLE
Convert code to Python 3

### ISSUE THREAD

**Issue by evan-magnusson** [open-source-economics/OG-USA#45]
Make the code Python 3 compatible.

**Comment by evan-magnusson** [comment]
Do we want the code to be compatible with either Python 2.7 or 3, or just pick one or the other?

**Comment by jdebacker** [comment]
I don't know. @talumbau what do you suggest?

**Comment by MattHJensen** [comment]
Taxcalc is compatible with both python 2 and python 3 and run tests in both environments. I'd suggest the same for dynamic unless it presents a major challenge.

**Comment by evan-magnusson** [comment]
It shouldn't be too difficult.  I don't know much about Python 3, but the only things I can think of at the moment that might take extra care will be the times when we wanted to do integer division (for indexing, usually), and now that will no longer be the default.  But those are limited cases, and probably pretty easy to track down.

**Comment by PeterDSteinberg** [comment]
I think this issue @evan-magnusson raises regarding Python 3 support for OG-USA makes sense given that taxcalc supports Python 3 and B-Tax will shortly.  It would be nice to have the three packages cooperate in conda env's that are 2.7, 3.4, 3.5. @MattHJensen @jdebacker I'll assign this issue to myself.

**Comment by jdebacker** [comment]
@PeterDSteinberg Sounds good.  Thanks for taking this on.

A couple thoughts:
1) Should we wait until the regression testing of 0.5.6 is done?
2) Could we wait until I fix what I think are a couple bugs in the code (See Issues #284 and #283)?  I'm working on this.  Hopefully have a solution early next week.

**Comment by PeterDSteinberg** [comment]
@jdebacker Waiting until next week sounds good - it will take me a bit to resolve the B-Tax Python 3 issues today / Monday perhaps.

**Comment by rickecon** [comment]
Most of the steps in converting OG-USA to run with Python 3.5+ are to simply change any print commands to `print()`. I would be surprised if that constituted less than 90% of the substance. @jdebacker @PeterDSteinberg

**Comment by jdebacker** [comment]
Agree with @rickecon,  but want as little to change as possible while I work out these bugs.  It's already been taking me too long!

**Comment by jdebacker** [comment]
Closed in just under 3 years (!) with PR #367.
