### ISSUE TITLE
TPI Euler equations as functions

### ISSUE THREAD

**Issue by evan-magnusson** [open-source-economics/OG-USA#50]
In TPI, all the euler equations are not functions.  We might want to change this so we only have to change the euler equations in one place.

**Comment by evan-magnusson** [comment]
We could use the same euler equation functions as the SS does, but add inputs for b_s_t, b_s_tplus1, etc.  Then, it would work for TPI (assuming it has the right shapes), and in SS we would just put the same value for b_s_t and b_s_tplus1.

**Comment by jdebacker** [comment]
Resolved in PR #349
