### ISSUE TITLE
Error in calculating replacement rates for payroll tax

### ISSUE THREAD

**Issue by evan-magnusson** [open-source-economics/OG-USA#73]
In the replacement_rate_vals() function in the tax.py file there is a bug of sorts.  When we get the replacement rates, all but the lowest 25% of individuals hit the maximum payment.  It is unlikely that   the bottom 50% and above are making more than 30K a month, so there must be either a problem in the code itself, or the data/method we used to calculate the bins of the PIA.

**Comment by evan-magnusson** [comment]
Since we have the top 1% of the distribution, it is likely that the factor is scaling things up to much.

**Comment by jdebacker** [comment]
This has been fixed.  Most recently with PR #261
