### ISSUE TITLE
Fix immigration rates problem

### ISSUE THREAD

**Issue by evan-magnusson** [open-source-economics/OG-USA#87]
Unless the immigration rates are zero, the resource constraint is violated.  Since immigration rates are only used in 3 functions in demographics.py, this should be easy to fix.   Until the problem is found, the immigration rates have been set to zero.  (in the get_omega() function in demographics.py, after the immigration rates function is used, the immigration rates are multiplied by 0).

**Comment by jdebacker** [comment]
This problem has been sorted since about June 2016.
