### ISSUE TITLE
Marginal utility of labor function try/except

### ISSUE THREAD

**Issue by evan-magnusson** [open-source-economics/OG-USA#95]
As talked about in the comments on PR #94 , we need to add some flags so that the try/except changes the deriv only in certain circumstances (this is the marg_ut_labor function in house.py).  @talumbau knows where this is.  I think the 'permissive' flag is a good idea, and we can have it just run normally when running the 'real' code.

**Comment by jdebacker** [comment]
Closing.  I don't think this has been an issue but there is a note in the code that will remind us if there is one.
